# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dynamic Valley
contact: ShipStan
email: shipstan@dynamicvalley.com.au
description: > # this means to ignore newlines until "baseurl:"
  Dynamic Valley commits to build bridges between Dynamians and Dynamic Stores. 
  Dynamians can search for Dynamic Stores to fulfill their needs in Dynamic Valley.
  Join Dynamic Valley and make your life more dynamic!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: shipstan
github_username:  shipstan
facebook_username: ShipStan

# Build settings
markdown: kramdown
